meta_product_name: "Jonathan Wagner"
meta_title: "Jonathan Wagner"
meta_description: "Portfolio of Jonathan Wagner - Full Stack Web Developer and Project Manager"
meta_image: "portfolio.png" # should exist in `app/assets/images/`
twitter_account: "@USERNAME"   # required for Twitter Cards
